name: BUILD PRODUCAO METODISTA APP

on:
  push:
    branches: [master]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build application to production
        run: npm run build

      - name: Envia para o SURGE
      - run: npm install -g surge
      - run: surge ./ ${{ secrets.SURGE_DOMAIN_METODISTA_APP }} --token ${{ secrets.SURGE_TOKEN_METODISTA_APP }}
